# Laboratorio 3
Estuardo Diaz, 16110


In [1]:
import numpy as np
from scipy import linalg
import matplotlib
import matplotlib.pyplot as plt

### Problema 1

In [2]:
def Jacobi(A,b,x0,N=100,tol=0.001):
    for k in range(N):
        print(k,": ", x0)
        x = np.zeros_like(x0)
        for i in range(A.shape[0]):
            x[i] = (b[i] - sum(A[i,:]*x0) + A[i,i]*x0[i]) / A[i, i]
        if np.allclose(x0, x, atol=tol, rtol=0.):
            return x
        x0 = x
    print("Se excedió el número máximo de iteraciones")
    return x

In [3]:
def GaussSeidel(A,b,x0,N=100,tol=0.001):
    for k in range(N):
        print(k,": ",x0)
        x = np.zeros_like(x0)
        for i in range(A.shape[0]):
            x[i] = (b[i] - sum(A[i, :i]*x[:i]) - sum(A[i, i + 1:]*x0[i + 1:])) / A[i, i]
        if np.allclose(x0, x, rtol=tol):
            return x
        x0 = x
    print("Se excedió el número máximo de iteraciones")
    return x

In [4]:
def SOR(A, b, x0, w=0.5, N=100, tol=0.001):
    x = x0
    for k in range(N):
        print(k,": ",x0)
        for i in range(A.shape[0]):
            x[i] = (1 - w) * x[i] + (w / A[i][i]) * (b[i] - sum(A[i,:]*x) + A[i,i]*x[i])
        if np.linalg.norm(np.matmul(A, x) - b) < tol:
            return x
    print("Se excedió el número máximo de iteraciones")
    return x

In [5]:
def radioEspectral(A):
    return max(linalg.eigvals(A))

In [6]:
A = np.array([[10,-1,2,0],[-1,11,-1,3],[2,-1,10,-1],[0,3,-1,8]])
b = np.array([6,25,-11,4])
x0 = np.transpose(np.zeros(4))
rho = radioEspectral(A)

print("rho(A): ",rho)
x = Jacobi(A,b,x0,50,0.000001)

print("Ax - b:\n", A.dot(x))

rho(A):  (14.073477752817427+0j)
0 :  [0. 0. 0. 0.]
1 :  [ 0.6         2.27272727 -1.1         0.5       ]
2 :  [ 1.04727273  2.09090909 -0.94272727 -0.48977273]
3 :  [ 0.99763636  2.41580579 -1.14934091 -0.40193182]
4 :  [ 1.07144876  2.36855372 -1.09813988 -0.54959478]
5 :  [ 1.05648335  2.42019029 -1.13239386 -0.52547513]
6 :  [ 1.0684978   2.40913772 -1.12182515 -0.54912059]
7 :  [ 1.0652788   2.41763949 -1.12769785 -0.54365479]
8 :  [ 1.06730352  2.4153223  -1.12565729 -0.54757704]
9 :  [ 1.06666369  2.41676158 -1.12668618 -0.54645302]
10 :  [ 1.06701339  2.41630333 -1.12630188 -0.54712136]
11 :  [ 1.06689071  2.41655233 -1.12648448 -0.54690148]
12 :  [ 1.06695213  2.41646461 -1.12641306 -0.54701768]
13 :  [ 1.06692907  2.41650837 -1.12644573 -0.54697586]
14 :  [ 1.06693998  2.4164919  -1.12643256 -0.54699636]
15 :  [ 1.0669357   2.41649968 -1.12643844 -0.54698853]
16 :  [ 1.06693766  2.41649662 -1.12643603 -0.54699219]
17 :  [ 1.06693687  2.41649802 -1.12643709 -0.54699074]
Ax - 

### Problema 2

In [16]:
A = np.array([[4,3,0],[3,4,-1],[0,-1,4]])
b= np.array([[24],[30],[-24]])

### Problema 3

In [12]:
A = np.array([[4,3,0],[3,4,-1],[0,-1,4]])
print("A:\n",A)
print("Eigenvalores:", linalg.eigvals(A))

A:
 [[ 4  3  0]
 [ 3  4 -1]
 [ 0 -1  4]]
Eigenvalores: [0.83772234+0.j 7.16227766+0.j 4.        +0.j]


Como los eigenvalores son positivos, entonces la matriz es definida positiva

### Problema 4

### Problema 5

In [15]:
A = -1*np.ones((4,4)) + np.diag(np.ones(4)*5)
A

array([[ 4., -1., -1., -1.],
       [-1.,  4., -1., -1.],
       [-1., -1.,  4., -1.],
       [-1., -1., -1.,  4.]])